# wget https://raw.githubusercontent.com/rancher/k3s/master/docker-compose.yml
version: '3'
services:
  k3s-server:
    image: rancher/k3s:v0.8.1
    container_name: k3s-server
    command: server --disable-agent --no-deploy traefik
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
      - 6443:6443
    network_mode: bridge

  k3s-worker:
    image: rancher/k3s:v0.10.2
    container_name: k3s-worker
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://k3s-server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
    network_mode: bridge
    links:
      - k3s-server

volumes:
  k3s-server: {}
